<?php

declare(strict_types=1);

namespace Polymorph\Platform\Support\Errors;

enum ErrorCode: string
{
    case BAD_REQUEST = 'BAD_REQUEST';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';
    case NOT_FOUND = 'NOT_FOUND';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case CONFLICT = 'CONFLICT';
    case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
    case SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

    case INVALID_PLUGIN_MANIFEST = 'INVALID_PLUGIN_MANIFEST';

    case MEDIA_DOWNLOAD_ERROR = 'MEDIA_DOWNLOAD_ERROR';
    case MEDIA_STORAGE_ERROR = 'MEDIA_STORAGE_ERROR';
    case MEDIA_VARIANT_ERROR = 'MEDIA_VARIANT_ERROR';

    case CSRF_TOKEN_MISMATCH = 'CSRF_TOKEN_MISMATCH';

}
