<?php

declare(strict_types=1);

namespace Polymorph\Platform\Domain\AccessControl\Console;

use Illuminate\Console\Command;
use Polymorph\Platform\Domain\AccessControl\Services\CapabilityRegistry;

/**
 * Генерирует фронтовый каталог capability-ключей из бэкендового реестра.
 *
 * До него fe/src/access/capabilities.ts дублировал каталог руками, и любое
 * переименование на бэке (как unify-миграция этапа 1) требовало синхронной
 * ручной правки фронта — рассинхрон обнаруживался только глазами. Теперь
 * источник один: `--check` в CI падает, если сгенерированный файл устарел.
 *
 * Динамические capability расширений (`ext.*`) намеренно не включаются:
 * фронт получает их в рантайме через /auth/current, а каталог описывает ядро.
 */
final class GenerateFeCapabilityCatalogCommand extends Command
{
    protected $signature = 'access-control:generate-fe-catalog {--check : Проверить актуальность без записи} {--path= : Куда писать (для тестов)}';

    protected $description = 'Generate fe/src/access/capabilities.generated.ts from the backend capability registry';

    public function handle(CapabilityRegistry $registry): int
    {
        $keys = [];

        foreach ($registry->capabilityDefinitionsAsArrays() as $definition) {
            $resource = $definition['resource'];
            $action = $definition['action'];

            if (str_starts_with($resource, 'ext.')) {
                continue;
            }

            $keys[] = $resource.'/'.$action;
        }

        sort($keys, SORT_STRING);
        $keys = array_values(array_unique($keys));

        $content = $this->render($keys);
        $path = $this->targetPath();

        if ((bool) $this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : '';

            if (trim($current) !== trim($content)) {
                $this->error('FE capability catalog is stale. Run: php artisan access-control:generate-fe-catalog');

                return self::FAILURE;
            }

            $this->info('FE capability catalog is up to date.');

            return self::SUCCESS;
        }

        file_put_contents($path, $content);
        $this->info("Written: {$path}");

        return self::SUCCESS;
    }

    /**
     * @param  list<string>  $keys
     */
    private function render(array $keys): string
    {
        $lines = array_map(static fn (string $key): string => "  '{$key}',", $keys);

        return "// AUTO-GENERATED by `php artisan access-control:generate-fe-catalog` — do not edit.\n"
            ."// Источник: бэкендовый CapabilityRegistry (core-домены, без плагинов).\n"
            ."export const KNOWN_CAPABILITIES = [\n"
            .implode("\n", $lines)."\n"
            ."] as const;\n\n"
            ."export type KnownCapability = (typeof KNOWN_CAPABILITIES)[number];\n";
    }

    private function targetPath(): string
    {
        $override = $this->option('path');
        if (is_string($override) && trim($override) !== '') {
            return $override;
        }

        return base_path('../fe/src/access/capabilities.generated.ts');
    }
}
